language: ruby
rvm:
- 2.2
sudo: required
before_install:
# Decrypt important files
- openssl aes-256-cbc -K $encrypted_fc456133d54b_key -iv $encrypted_fc456133d54b_iv
  -in .cfcli.yml.enc -out ~/.cfcli.yml -d
- openssl aes-256-cbc -K $encrypted_0c41919e9cd0_key -iv $encrypted_0c41919e9cd0_iv
  -in deploy-key.enc -out deploy-key -d
# Start ssh agent, add key and add fingerprint to known host
- eval `ssh-agent -s`
- chmod 600 deploy-key && ssh-add deploy-key && rm deploy-key
- bash _scripts/ssh_autenticity.sh
# Cute script to notify us
- sudo cp _scripts/slack_message.sh /usr/local/bin/ && sudo chmod +x /usr/local/bin/slack_message.sh
# Install latest nginx development
- sudo add-apt-repository -y ppa:nginx/development
- sudo apt-get update
- sudo apt-get -qq -y install nginx zip
# Install latest node.js
- sudo apt-get remove -qq -y nodejs
- curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
- sudo apt-get install -qq -y nodejs
- nvm install node
- source ~/.bashrc
- npm install npm -g
# Tools
- npm install -g cloudflare-cli

install:
# Install ruby
- bundle install
# Fermiumlabs.com nodejs stuff
- sh -c "cd Websites/fermiumlabs_com && npm install"
script:
# Fermiumlabs.com
- sh -c "cd Websites/fermiumlabs_com && gulp build-deploy"
# Test Nginx config
- bash _scripts/tests/nginx/nginx.sh
# Test html
- bash _scripts/tests/html/htmlproofer.sh


after_success:
# If master and not a pull request, deploy
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  _scripts/deploy.sh
# If develop and not a pull request, deploy
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "develop" && bash
  _scripts/deploy.sh
# If master and not a pull request, deploy Nginx config
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  _scripts/deploy_config.sh
# If master and not a pull request, clear cloudflare cache
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && cfcli purgecache
# Zip and upload to transfer.sh
# BEWARE NOT TO ZIP OUTSIDE THE "Websited" dir!
- zip -r fermiumlabs_com.zip Websites/fermiumlabs_com/_site
- curl --upload-file ./fermiumlabs_com.zip https://transfer.sh/fermiumlabs_com.zip  >>
  slack_message.txt
# Notify dev team
- slack_message.sh -t "Deployed" -b "$(cat slack_message.txt)" -c "repositories" -u
  "$SLACK_WEBHOOK_URL"
  

notifications:
  slack:
    on_success: always
    on_start: always
    rooms:
      secure: R35J/HeR/8Gj1xz/6leLx6yaKn6FujyfItoYKb6olpIthEayKexy1OSahjUOy0Euq7QmTrdOLM2ZlRjAUTg11ea75oO47U1bV58gQtz1UPhBJHAMO3B2Puuop2f7AmaAw5IEwRrUVtDD+ihS+oErbJR+JJK8FcpmWNTOfr77Ei/xjqgs9EZnwgDdS7RMowsfKxyDdIq1uU6FT4VckSBbfAknuVdK1tmF6H5RsitA74EMeuQ+nor+SlWZSt3G2aRwowv5hcXm9t6Oq+8pa2dVweYPt+p833gFh0hh2oqHo5KQYUfXiOrt2pSkjW83mhip458XnvrjlxlHIYZKdff3334Rv2Rl0Jjqxugn+foYnLTuB+z93BY401tC6TooVUbqXkbW8TAu89xeHNOhltm0XVXWsTNvciIStZ+C94UZSRV0XksBvWDFCmIJqnQPSOBFiccOU7X0UUpCuNRF5R3OHj3wkPgWsYlUOixUtPq9HxX0VayXKobZgJ4me7ayIaqax4uV5tAqBVRA0tS3lnkWWwkFSpdLqKXdplR+efenN27/XRYplsa3j0YkHsoNPLLHiSj5KIlZioh/pNRigJ1uZQ7LqlwKv1dhB69L0Ws3+7lKOoqnnqfJhUmZVu/wMZOv9cmS9BVfYjNZn+5njjSBwpdl4Iqsxh2qr3XjCaUyoVE=
  email: false
  

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
