#based on https://kjaermaxi.me/travis/
language: ruby
rvm:
- 2.1
sudo: required
before_install:
- bash _scripts/ssh_autenticity.sh
- sudo add-apt-repository -y ppa:nginx/stable
- sudo apt-get update
- openssl aes-256-cbc -K $encrypted_0c41919e9cd0_key -iv $encrypted_0c41919e9cd0_iv
  -in deploy-key.enc -out deploy-key -d
- eval `ssh-agent -s`
- chmod 600 deploy-key && ssh-add deploy-key && rm deploy-key.enc && rm deploy-key
- sudo cp _scripts/slack_message.sh /usr/local/bin/ && sudo chmod +x /usr/local/bin/slack_message.sh
install:
- sudo apt-get -qq -y install nginx
- gem install jekyll html-proofer
script:
- jekyll clean && jekyll build
- bash _scripts/deploy.sh
after_success:
- echo nothing to do
branches:
  only:
  - master
  - develop
notifications:
  slack:
    on_success: always
    rooms:
      secure: R35J/HeR/8Gj1xz/6leLx6yaKn6FujyfItoYKb6olpIthEayKexy1OSahjUOy0Euq7QmTrdOLM2ZlRjAUTg11ea75oO47U1bV58gQtz1UPhBJHAMO3B2Puuop2f7AmaAw5IEwRrUVtDD+ihS+oErbJR+JJK8FcpmWNTOfr77Ei/xjqgs9EZnwgDdS7RMowsfKxyDdIq1uU6FT4VckSBbfAknuVdK1tmF6H5RsitA74EMeuQ+nor+SlWZSt3G2aRwowv5hcXm9t6Oq+8pa2dVweYPt+p833gFh0hh2oqHo5KQYUfXiOrt2pSkjW83mhip458XnvrjlxlHIYZKdff3334Rv2Rl0Jjqxugn+foYnLTuB+z93BY401tC6TooVUbqXkbW8TAu89xeHNOhltm0XVXWsTNvciIStZ+C94UZSRV0XksBvWDFCmIJqnQPSOBFiccOU7X0UUpCuNRF5R3OHj3wkPgWsYlUOixUtPq9HxX0VayXKobZgJ4me7ayIaqax4uV5tAqBVRA0tS3lnkWWwkFSpdLqKXdplR+efenN27/XRYplsa3j0YkHsoNPLLHiSj5KIlZioh/pNRigJ1uZQ7LqlwKv1dhB69L0Ws3+7lKOoqnnqfJhUmZVu/wMZOv9cmS9BVfYjNZn+5njjSBwpdl4Iqsxh2qr3XjCaUyoVE=
  email: false
