# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fermium LABS
email: info@fermiumlabs.com
description: > # this means to ignore newlines until "baseurl:"
  Fermium LABS srl is a company dedicated to exploiting young mind views and new technologies for the sake of innovation.
  (Our own, by the way)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fermiumlabs.com" # the base hostname & protocol for your site
twitter_username: "@fermiumlabs"
github_username:  fermiumlabs
# Build settings
markdown: kramdown

# Generate files to be used withouth .html extension
permalink: pretty

exclude: ["_app",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json",
          "*.scss",
          "*.less",
          "*.js"]
# Don't forget that Jekyll automatically
# excludes files with a dot prefix
